[versions]
agp = "9.1.0"

# AndroiX
activity = "1.13.0"
## https://developer.android.com/develop/ui/compose/bom/bom-mapping
compose-bom = "2026.03.00"
lifecycle = "2.11.0-alpha02"
room = "2.8.4"
paging = "3.5.0-alpha01"
nav3Core = "1.1.0-beta01"

# 3rd-party
dagger = "2.59.2"
kotlin = "2.3.20"
ksp = "2.3.6"
kotlin-coroutine = "1.10.2"
okhttp = "5.3.2"

[libraries]
# AndroidX
androidX-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidX-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidX-arch-coreTesting = "androidx.arch.core:core-testing:2.2.0"
androidX-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidX-browser = "androidx.browser:browser:1.10.0-rc01"
androidX-core-ktx = "androidx.core:core-ktx:1.18.0"
androidX-core-splashScreen = "androidx.core:core-splashscreen:1.2.0"
androidX-compose-bom = { module = "androidx.compose:compose-bom-alpha", version.ref = "compose-bom" }
androidX-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidX-compose-liveData = { module = "androidx.compose.runtime:runtime-livedata" }
androidX-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidX-compose-material3 = { module = "androidx.compose.material3:material3" }
androidX-compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
androidX-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidX-compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidX-compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidX-compose-ui = { module = "androidx.compose.ui:ui" }
androidX-compose-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidX-compose-ui-test = { module = "androidx.compose.ui:ui-test" }
androidX-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidX-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.1.1"
androidX-fragment-ktx = "androidx.fragment:fragment-ktx:1.8.9"
androidX-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.3.0"
androidX-lifecycle-runtimeTesting = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "lifecycle" }
androidX-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidX-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }
androidX-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidX-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidX-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidX-palette = "androidx.palette:palette:1.0.0"
androidX-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidX-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
androidX-preference = "androidx.preference:preference:1.2.1"
androidX-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidX-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidX-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidX-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidX-test-junit = "androidx.test.ext:junit:1.3.0"
androidX-test-espresso = "androidx.test.espresso:espresso-core:3.7.0"
androidX-viewBinding = { module = "androidx.databinding:viewbinding", version.ref = "agp" }
# 3rd-party
## Dagger
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
## Kotlin
kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutine" }
kotlin-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutine" }
kotlin-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutine" }
kotlin-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
## etc
jsoup = "org.jsoup:jsoup:1.22.1"
landscapist = "com.github.skydoves:landscapist-coil:2.9.5"
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
timber = "com.jakewharton.timber:timber:5.0.1"

junit = "junit:junit:4.13.2"
assertJ = "org.assertj:assertj-core:3.27.6"
mockito = "org.mockito:mockito-core:5.20.0"

# Dependencies of the included build-logic
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "dagger" }
compose-compiler-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }

[bundles]
androidX-navigation = [
    "androidX-navigation3-runtime",
    "androidX-navigation3-ui"
]

androidX-compose = [
    "androidX-compose-foundation",
    "androidX-compose-liveData",
    "androidX-compose-material-icons-core",
    "androidX-compose-material3",
    "androidX-compose-material3-windowSizeClass",
    "androidX-compose-runtime",
    "androidX-compose-toolingPreview",
    "androidX-compose-ui",
    "androidX-lifecycle-runtime-compose"
]

androidX-compose-debug = [
    "androidX-compose-tooling",
    "androidX-compose-uiTestManifest"
]

androidX-compose-ui-test = [
    "androidX-compose-ui-test",
    "androidX-compose-ui-test-junit4"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
cacheFixPlugin = { id = "org.gradle.android.cache-fix", version = "3.0.2" }