[versions]
androidStudioGradlePlugin = "7.3.0-beta04"

# AndroiX
activity = "1.5.0-rc01"
compose = "1.2.0-rc02"
composeCompiler = "1.2.0-rc02"
lifecycle = "2.5.0-rc02"
room = "2.4.2"

# 3rd-party
accompanist = "0.24.12-rc"
coil = "2.1.0"
dagger = "2.42"
kotlin = "1.6.21"
ksp = "1.6.21-1.0.6"
kotlin-coroutine = "1.6.3"
okhttp = "4.9.3"

[libraries]
plugin-androidGradle = { module = "com.android.tools.build:gradle", version.ref = "androidStudioGradlePlugin" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# AndroidX
androidX-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidX-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidX-arch-coreTesting = "androidx.arch.core:core-testing:2.1.0"
androidX-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidX-core-ktx = "androidx.core:core-ktx:1.8.0"
androidX-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidX-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidX-compose-liveData = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidX-compose-material = "androidx.compose.material3:material3:1.0.0-alpha13"
androidX-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidX-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidX-compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidX-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidX-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.0.1"
androidX-customview-poolingcontainer = "androidx.customview:customview-poolingcontainer:1.0.0-rc01"
androidX-browser = "androidx.browser:browser:1.4.0"
androidX-fragment = "androidx.fragment:fragment:1.5.0-rc01"
androidX-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidX-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidX-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidX-lifecycle-runtimeTesting = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "lifecycle" }
androidX-navigation-compose = "androidx.navigation:navigation-compose:2.5.0-rc02"
androidX-palette = "androidx.palette:palette:1.0.0"
androidX-paging-runtime = "androidx.paging:paging-runtime:3.1.1"
androidX-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha15"
androidX-preference = "androidx.preference:preference:1.2.0"
androidX-recyclerview = "androidx.recyclerview:recyclerview:1.3.0-alpha02"
androidX-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidX-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidX-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidX-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidX-splashScreen = "androidx.core:core-splashscreen:1.0.0-rc01"
androidX-test-junit = "androidx.test.ext:junit:1.1.3"
androidX-test-espresso = "androidx.test.espresso:espresso-core:3.4.0"
androidX-viewBinding = { module = "androidx.databinding:viewbinding", version.ref = "androidStudioGradlePlugin" }
androidX-window = "androidx.window:window:1.0.0"
# 3rd-party
## Accompanist
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-systemUi = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
## Dagger
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
## Kotlin
kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutine" }
kotlin-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutine" }
kotlin-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutine" }
kotlin-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3"
## etc
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
jsoup = "org.jsoup:jsoup:1.14.3"
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
timber = "com.jakewharton.timber:timber:5.0.1"

junit = "junit:junit:4.13.2"
assertJ = "org.assertj:assertj-core:3.23.1"
mockito = "org.mockito:mockito-core:4.6.1"
javapoet = "com.squareup:javapoet:1.13.0"

[bundles]
androidX-compose = [
    "androidX-compose-animation",
    "androidX-compose-foundation",
    "androidX-compose-liveData",
    "androidX-compose-material",
    "androidX-compose-runtime",
    "androidX-compose-toolingPreview"
]

androidX-compose-preview = [
    "androidX-compose-tooling",
    "androidX-customview-poolingcontainer"
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidStudioGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidStudioGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }