query contentHomeProductList($after: String, $before: String, $first: Int, $last: Int, $seriesId: Long!, $boughtOnly: Boolean, $sortType: String) {
  contentHomeProductList(
    seriesId: $seriesId
    after: $after
    before: $before
    first: $first
    last: $last
    boughtOnly: $boughtOnly
    sortType: $sortType
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
      node {
        ...SingleListViewItem
      }
    }
  }
}

    fragment SingleListViewItem on SingleListViewItem {
  id
  type
  thumbnail
  showPlayerIcon
  isCheckMode
  isChecked
  scheme
  row1
  row2
  row3 {
    badgeList
    text
    priceList
  }
  single {
    productId
    ageGrade
    id
    isFree
    thumbnail
    title
    slideType
    operatorProperty {
      isTextViewer
    }
  }
  isViewed
  discountRate
  discountRateText
}