name: pull request review

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5
          arguments: lintDebug

      - name: Set up and run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install danger
          gem install danger-checkstyle_format
          gem install danger-android_lint
          bundle exec danger