name: pull request review

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Set up and run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install danger
          gem install danger-checkstyle_format
          gem install danger-android_lint
          bundle exec danger